[colors.bright]
black = "#666666"
blue = "#0000FF"
cyan = "#00E5E5"
green = "#00D900"
magenta = "#E500E5"
red = "#E50000"
white = "#E5E5E5"
yellow = "#E5E500"

[colors.normal]
black = "#000000"
blue = "#0000B2"
cyan = "#00A6B2"
green = "#00A600"
magenta = "#B200B2"
red = "#990000"
white = "#BFBFBF"
yellow = "#999900"

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"
